title: x3
services:
  - priority: 0
    game: "0x5d6fd9f54085490457cd534d4bdf90289fae65a7"
    name: "snake3"
    image: "snake_image:latest"
    ports:
      - host: 6663
        target: 8080
      - host: 6603
        target: 3306
      - host: 6633
        target: 5005
    detached: true
    type: "ETH"

  - priority: 1
    game: "0xf677e4051eeff7a60598cc6419b982cdeef60b01"
    name: "mixmarvel3"
    image: "mixmarvel_image:latest"
    ports:
      - host: 5553
        target: 8080
    detached: true
    type: "ETH"

  - priority: 2
    game: "0xc37a349ba8f91f8cd4da47c087b6bbc571d4e7ef"
    name: "genesis3"
    image: "genesis_image:latest"
    ports:
      - host: 7773
        target: 8080
    detached: true
    type: "ETH"