title: x5
services:
  - priority: 0
    game: "tuntunbiu"
    name: "tuntunbiu5"
    image: "tuntunbiu_image:latest"
    ports:
      - host: 8885
        target: 8080
    detached: true

  - priority: 1
    game: "appid_demo_1"
    name: "appid_demo_1_5"
    image: "state_machine_demo_js:latest"
    ports:
      - host: 7775
        target: 7001
    detached: true
    cmd: "npm start"