title: test
services:
  - priority: 0
    game: "j"
    name: "j1"
    image: "tcsm_state_machine:68"
    ports:
      - host: 8888
        target: 80
    detached: true
    cmd: "npm start"

  - priority: 1
    game: "abc"
    image: "state_machine_demo_tuntun:latest"
    ports:
      - host: 8866
        target: 8080
    detached: true
