title: x1
services:
  - priority: 0
    game: "tuntunbiu"
    name: "tuntunbiu1"
    image: "tuntunbiu_image:latest"
    ports:
      - host: 8881
        target: 8080
    detached: true

  - priority: 1
    game: "snake"
    name: "snake1"
    image: "snake_image:latest"
    ports:
      - host: 6661
        target: 8080
      - host: 6601
        target: 3306
    detached: true