title: x2
services:
  - priority: 0
    game: "0x5d6fd9f54085490457cd534d4bdf90289fae65a7"
    name: "snake2"
    image: "snake_image:latest"
    ports:
      - host: 6662
        target: 8080
      - host: 6602
        target: 3306
    detached: true