title: x3
services:
  - priority: 0
    game: "tuntunbiu"
    name: "tuntunbiu3"
    image: "tuntunbiu_image:latest"
    ports:
      - host: 8883
        target: 8080
    detached: true


  - priority: 1
    game: "snake"
    name: "snake3"
    image: "snake_image:latest"
    ports:
      - host: 6663
        target: 8080
      - host: 6653
        target: 3306
    detached: true