title: x3
services:
  - priority: 0
    game: "snake"
    name: "snake3"
    image: "snake_image:latest"
    ports:
      - host: 6663
        target: 8080
      - host: 6603
        target: 3306
    detached: true