// Code generated by protoc-gen-go. DO NOT EDIT.
// source: x.proto

/*
Package middleware_pb is a generated protocol buffer package.

It is generated from these files:
	x.proto

It has these top-level messages:
	Message
	Transaction
	TransactionRequestMessage
	TrieNodes
	TransactionSlice
	ChainPieceInfo
	BlockHeader
	BlockBody
	Block
	BlockSlice
	Member
	GroupHeader
	Group
	GroupInfo
	GroupSlice
	GroupIdSlice
	GroupRequestInfo
	Hashes
	TotalQnInfo
	StateInfoReq
	StateInfo
	TrieNode
	SignData
	ConsensusGroupInitSummary
	PubKeyInfo
	ConsensusGroupInitInfo
	ConsensusGroupRawMessage
	SharePiece
	ConsensusSharePieceMessage
	ConsensusSignPubKeyMessage
	ConsensusSignPubkeyReqMessage
	StaticGroupSummary
	ConsensusGroupInitedMessage
	ConsensusCurrentMessage
	ConsensusCastMessage
	ConsensusVerifyMessage
	ConsensusBlockMessage
	ConsensusCreateGroupRawMessage
	ConsensusCreateGroupSignMessage
	TopBlockInfo
	BlockMsgResponse
	ChainPieceBlockMsg
	CreateGroupPingMessage
	CreateGroupPongMessage
	ReqSharePieceMessage
	ResponseSharePieceMessage
	SubAccount
*/
package middleware_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Code             *uint32 `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Body             []byte  `protobuf:"bytes,2,opt,name=Body" json:"Body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Transaction struct {
	Data             *string  `protobuf:"bytes,1,req,name=Data" json:"Data,omitempty"`
	Nonce            *uint64  `protobuf:"varint,2,opt,name=Nonce" json:"Nonce,omitempty"`
	Source           []byte   `protobuf:"bytes,3,opt,name=Source" json:"Source,omitempty"`
	Target           *string  `protobuf:"bytes,4,req,name=Target" json:"Target,omitempty"`
	Type             *int32   `protobuf:"varint,5,req,name=Type" json:"Type,omitempty"`
	Hash             []byte   `protobuf:"bytes,6,opt,name=Hash" json:"Hash,omitempty"`
	ExtraData        []byte   `protobuf:"bytes,7,opt,name=ExtraData" json:"ExtraData,omitempty"`
	ExtraDataType    *int32   `protobuf:"varint,8,opt,name=ExtraDataType" json:"ExtraDataType,omitempty"`
	Sign             []byte   `protobuf:"bytes,9,opt,name=Sign" json:"Sign,omitempty"`
	Time             *string  `protobuf:"bytes,10,opt,name=Time" json:"Time,omitempty"`
	RequestId        *uint64  `protobuf:"varint,11,opt,name=RequestId" json:"RequestId,omitempty"`
	SocketRequestId  *string  `protobuf:"bytes,12,opt,name=SocketRequestId" json:"SocketRequestId,omitempty"`
	SubTransactions  []string `protobuf:"bytes,13,rep,name=SubTransactions" json:"SubTransactions,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Transaction) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *Transaction) GetSource() []byte {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Transaction) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return ""
}

func (m *Transaction) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *Transaction) GetExtraDataType() int32 {
	if m != nil && m.ExtraDataType != nil {
		return *m.ExtraDataType
	}
	return 0
}

func (m *Transaction) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Transaction) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

func (m *Transaction) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *Transaction) GetSocketRequestId() string {
	if m != nil && m.SocketRequestId != nil {
		return *m.SocketRequestId
	}
	return ""
}

func (m *Transaction) GetSubTransactions() []string {
	if m != nil {
		return m.SubTransactions
	}
	return nil
}

type TransactionRequestMessage struct {
	TransactionHashes [][]byte `protobuf:"bytes,1,rep,name=TransactionHashes" json:"TransactionHashes,omitempty"`
	CurrentBlockHash  []byte   `protobuf:"bytes,2,req,name=CurrentBlockHash" json:"CurrentBlockHash,omitempty"`
	BlockHeight       *uint64  `protobuf:"varint,3,req,name=BlockHeight" json:"BlockHeight,omitempty"`
	BlockPv           []byte   `protobuf:"bytes,4,req,name=BlockPv" json:"BlockPv,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *TransactionRequestMessage) Reset()                    { *m = TransactionRequestMessage{} }
func (m *TransactionRequestMessage) String() string            { return proto.CompactTextString(m) }
func (*TransactionRequestMessage) ProtoMessage()               {}
func (*TransactionRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransactionRequestMessage) GetTransactionHashes() [][]byte {
	if m != nil {
		return m.TransactionHashes
	}
	return nil
}

func (m *TransactionRequestMessage) GetCurrentBlockHash() []byte {
	if m != nil {
		return m.CurrentBlockHash
	}
	return nil
}

func (m *TransactionRequestMessage) GetBlockHeight() uint64 {
	if m != nil && m.BlockHeight != nil {
		return *m.BlockHeight
	}
	return 0
}

func (m *TransactionRequestMessage) GetBlockPv() []byte {
	if m != nil {
		return m.BlockPv
	}
	return nil
}

type TrieNodes struct {
	TrieNodes        []*TrieNode `protobuf:"bytes,1,rep,name=TrieNodes" json:"TrieNodes,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *TrieNodes) Reset()                    { *m = TrieNodes{} }
func (m *TrieNodes) String() string            { return proto.CompactTextString(m) }
func (*TrieNodes) ProtoMessage()               {}
func (*TrieNodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TrieNodes) GetTrieNodes() []*TrieNode {
	if m != nil {
		return m.TrieNodes
	}
	return nil
}

type TransactionSlice struct {
	Transactions     []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *TransactionSlice) Reset()                    { *m = TransactionSlice{} }
func (m *TransactionSlice) String() string            { return proto.CompactTextString(m) }
func (*TransactionSlice) ProtoMessage()               {}
func (*TransactionSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TransactionSlice) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type ChainPieceInfo struct {
	BlockHeaders     []*BlockHeader `protobuf:"bytes,1,rep,name=BlockHeaders" json:"BlockHeaders,omitempty"`
	TopHeader        *BlockHeader   `protobuf:"bytes,2,req,name=TopHeader" json:"TopHeader,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ChainPieceInfo) Reset()                    { *m = ChainPieceInfo{} }
func (m *ChainPieceInfo) String() string            { return proto.CompactTextString(m) }
func (*ChainPieceInfo) ProtoMessage()               {}
func (*ChainPieceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChainPieceInfo) GetBlockHeaders() []*BlockHeader {
	if m != nil {
		return m.BlockHeaders
	}
	return nil
}

func (m *ChainPieceInfo) GetTopHeader() *BlockHeader {
	if m != nil {
		return m.TopHeader
	}
	return nil
}

type BlockHeader struct {
	Hash             []byte  `protobuf:"bytes,1,opt,name=Hash" json:"Hash,omitempty"`
	Height           *uint64 `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	PreHash          []byte  `protobuf:"bytes,3,opt,name=PreHash" json:"PreHash,omitempty"`
	PreTime          []byte  `protobuf:"bytes,4,opt,name=PreTime" json:"PreTime,omitempty"`
	ProveValue       []byte  `protobuf:"bytes,5,opt,name=ProveValue" json:"ProveValue,omitempty"`
	TotalQN          *uint64 `protobuf:"varint,6,opt,name=TotalQN" json:"TotalQN,omitempty"`
	CurTime          []byte  `protobuf:"bytes,7,opt,name=CurTime" json:"CurTime,omitempty"`
	Castor           []byte  `protobuf:"bytes,8,opt,name=Castor" json:"Castor,omitempty"`
	GroupId          []byte  `protobuf:"bytes,9,opt,name=GroupId" json:"GroupId,omitempty"`
	Signature        []byte  `protobuf:"bytes,10,opt,name=Signature" json:"Signature,omitempty"`
	Nonce            *uint64 `protobuf:"varint,11,opt,name=Nonce" json:"Nonce,omitempty"`
	Transactions     *Hashes `protobuf:"bytes,12,opt,name=transactions" json:"transactions,omitempty"`
	TxTree           []byte  `protobuf:"bytes,13,opt,name=TxTree" json:"TxTree,omitempty"`
	ReceiptTree      []byte  `protobuf:"bytes,14,opt,name=ReceiptTree" json:"ReceiptTree,omitempty"`
	StateTree        []byte  `protobuf:"bytes,15,opt,name=StateTree" json:"StateTree,omitempty"`
	ExtraData        []byte  `protobuf:"bytes,16,opt,name=ExtraData" json:"ExtraData,omitempty"`
	Random           []byte  `protobuf:"bytes,17,opt,name=Random" json:"Random,omitempty"`
	ProveRoot        []byte  `protobuf:"bytes,18,opt,name=ProveRoot" json:"ProveRoot,omitempty"`
	EvictedTxs       *Hashes `protobuf:"bytes,19,opt,name=EvictedTxs" json:"EvictedTxs,omitempty"`
	RequestIds       []byte  `protobuf:"bytes,20,opt,name=RequestIds" json:"RequestIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BlockHeader) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *BlockHeader) GetPreTime() []byte {
	if m != nil {
		return m.PreTime
	}
	return nil
}

func (m *BlockHeader) GetProveValue() []byte {
	if m != nil {
		return m.ProveValue
	}
	return nil
}

func (m *BlockHeader) GetTotalQN() uint64 {
	if m != nil && m.TotalQN != nil {
		return *m.TotalQN
	}
	return 0
}

func (m *BlockHeader) GetCurTime() []byte {
	if m != nil {
		return m.CurTime
	}
	return nil
}

func (m *BlockHeader) GetCastor() []byte {
	if m != nil {
		return m.Castor
	}
	return nil
}

func (m *BlockHeader) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeader) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTransactions() *Hashes {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *BlockHeader) GetTxTree() []byte {
	if m != nil {
		return m.TxTree
	}
	return nil
}

func (m *BlockHeader) GetReceiptTree() []byte {
	if m != nil {
		return m.ReceiptTree
	}
	return nil
}

func (m *BlockHeader) GetStateTree() []byte {
	if m != nil {
		return m.StateTree
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *BlockHeader) GetRandom() []byte {
	if m != nil {
		return m.Random
	}
	return nil
}

func (m *BlockHeader) GetProveRoot() []byte {
	if m != nil {
		return m.ProveRoot
	}
	return nil
}

func (m *BlockHeader) GetEvictedTxs() *Hashes {
	if m != nil {
		return m.EvictedTxs
	}
	return nil
}

func (m *BlockHeader) GetRequestIds() []byte {
	if m != nil {
		return m.RequestIds
	}
	return nil
}

type BlockBody struct {
	BlockHash        []byte         `protobuf:"bytes,1,req,name=BlockHash" json:"BlockHash,omitempty"`
	Transactions     []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *BlockBody) Reset()                    { *m = BlockBody{} }
func (m *BlockBody) String() string            { return proto.CompactTextString(m) }
func (*BlockBody) ProtoMessage()               {}
func (*BlockBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BlockBody) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *BlockBody) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Block struct {
	Header           *BlockHeader   `protobuf:"bytes,1,req,name=Header" json:"Header,omitempty"`
	Transactions     []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockSlice struct {
	Blocks           []*Block `protobuf:"bytes,1,rep,name=Blocks" json:"Blocks,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BlockSlice) Reset()                    { *m = BlockSlice{} }
func (m *BlockSlice) String() string            { return proto.CompactTextString(m) }
func (*BlockSlice) ProtoMessage()               {}
func (*BlockSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BlockSlice) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Member struct {
	Id               []byte `protobuf:"bytes,1,req,name=Id" json:"Id,omitempty"`
	PubKey           []byte `protobuf:"bytes,2,req,name=PubKey" json:"PubKey,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Member) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Member) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type GroupHeader struct {
	Hash             []byte  `protobuf:"bytes,1,opt,name=Hash" json:"Hash,omitempty"`
	Parent           []byte  `protobuf:"bytes,2,opt,name=Parent" json:"Parent,omitempty"`
	PreGroup         []byte  `protobuf:"bytes,3,req,name=PreGroup" json:"PreGroup,omitempty"`
	Authority        *uint64 `protobuf:"varint,4,opt,name=Authority" json:"Authority,omitempty"`
	Name             *string `protobuf:"bytes,5,opt,name=Name" json:"Name,omitempty"`
	BeginTime        []byte  `protobuf:"bytes,6,opt,name=BeginTime" json:"BeginTime,omitempty"`
	MemberRoot       []byte  `protobuf:"bytes,7,opt,name=MemberRoot" json:"MemberRoot,omitempty"`
	CreateHeight     *uint64 `protobuf:"varint,8,opt,name=CreateHeight" json:"CreateHeight,omitempty"`
	ReadyHeight      *uint64 `protobuf:"varint,9,opt,name=ReadyHeight" json:"ReadyHeight,omitempty"`
	WorkHeight       *uint64 `protobuf:"varint,10,opt,name=WorkHeight" json:"WorkHeight,omitempty"`
	DismissHeight    *uint64 `protobuf:"varint,11,opt,name=DismissHeight" json:"DismissHeight,omitempty"`
	Extends          *string `protobuf:"bytes,12,opt,name=Extends" json:"Extends,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupHeader) Reset()                    { *m = GroupHeader{} }
func (m *GroupHeader) String() string            { return proto.CompactTextString(m) }
func (*GroupHeader) ProtoMessage()               {}
func (*GroupHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GroupHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *GroupHeader) GetParent() []byte {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *GroupHeader) GetPreGroup() []byte {
	if m != nil {
		return m.PreGroup
	}
	return nil
}

func (m *GroupHeader) GetAuthority() uint64 {
	if m != nil && m.Authority != nil {
		return *m.Authority
	}
	return 0
}

func (m *GroupHeader) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GroupHeader) GetBeginTime() []byte {
	if m != nil {
		return m.BeginTime
	}
	return nil
}

func (m *GroupHeader) GetMemberRoot() []byte {
	if m != nil {
		return m.MemberRoot
	}
	return nil
}

func (m *GroupHeader) GetCreateHeight() uint64 {
	if m != nil && m.CreateHeight != nil {
		return *m.CreateHeight
	}
	return 0
}

func (m *GroupHeader) GetReadyHeight() uint64 {
	if m != nil && m.ReadyHeight != nil {
		return *m.ReadyHeight
	}
	return 0
}

func (m *GroupHeader) GetWorkHeight() uint64 {
	if m != nil && m.WorkHeight != nil {
		return *m.WorkHeight
	}
	return 0
}

func (m *GroupHeader) GetDismissHeight() uint64 {
	if m != nil && m.DismissHeight != nil {
		return *m.DismissHeight
	}
	return 0
}

func (m *GroupHeader) GetExtends() string {
	if m != nil && m.Extends != nil {
		return *m.Extends
	}
	return ""
}

type Group struct {
	Header           *GroupHeader `protobuf:"bytes,1,req,name=Header" json:"Header,omitempty"`
	Id               []byte       `protobuf:"bytes,2,opt,name=Id" json:"Id,omitempty"`
	PubKey           []byte       `protobuf:"bytes,3,opt,name=PubKey" json:"PubKey,omitempty"`
	Signature        []byte       `protobuf:"bytes,4,opt,name=Signature" json:"Signature,omitempty"`
	Members          [][]byte     `protobuf:"bytes,5,rep,name=Members" json:"Members,omitempty"`
	GroupHeight      *uint64      `protobuf:"varint,6,opt,name=GroupHeight" json:"GroupHeight,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Group) GetHeader() *GroupHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Group) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Group) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Group) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Group) GetMembers() [][]byte {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Group) GetGroupHeight() uint64 {
	if m != nil && m.GroupHeight != nil {
		return *m.GroupHeight
	}
	return 0
}

type GroupInfo struct {
	Groups           []*Group `protobuf:"bytes,1,rep,name=Groups" json:"Groups,omitempty"`
	IsTopGroup       *bool    `protobuf:"varint,2,req,name=IsTopGroup" json:"IsTopGroup,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GroupInfo) Reset()                    { *m = GroupInfo{} }
func (m *GroupInfo) String() string            { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()               {}
func (*GroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GroupInfo) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *GroupInfo) GetIsTopGroup() bool {
	if m != nil && m.IsTopGroup != nil {
		return *m.IsTopGroup
	}
	return false
}

type GroupSlice struct {
	Groups           []*Group `protobuf:"bytes,1,rep,name=Groups" json:"Groups,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GroupSlice) Reset()                    { *m = GroupSlice{} }
func (m *GroupSlice) String() string            { return proto.CompactTextString(m) }
func (*GroupSlice) ProtoMessage()               {}
func (*GroupSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GroupSlice) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GroupIdSlice struct {
	GroupIds         [][]byte `protobuf:"bytes,1,rep,name=GroupIds" json:"GroupIds,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GroupIdSlice) Reset()                    { *m = GroupIdSlice{} }
func (m *GroupIdSlice) String() string            { return proto.CompactTextString(m) }
func (*GroupIdSlice) ProtoMessage()               {}
func (*GroupIdSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GroupIdSlice) GetGroupIds() [][]byte {
	if m != nil {
		return m.GroupIds
	}
	return nil
}

type GroupRequestInfo struct {
	CurrentTopGroupId []byte        `protobuf:"bytes,1,req,name=CurrentTopGroupId" json:"CurrentTopGroupId,omitempty"`
	ExistGroupIds     *GroupIdSlice `protobuf:"bytes,2,opt,name=ExistGroupIds" json:"ExistGroupIds,omitempty"`
	XXX_unrecognized  []byte        `json:"-"`
}

func (m *GroupRequestInfo) Reset()                    { *m = GroupRequestInfo{} }
func (m *GroupRequestInfo) String() string            { return proto.CompactTextString(m) }
func (*GroupRequestInfo) ProtoMessage()               {}
func (*GroupRequestInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GroupRequestInfo) GetCurrentTopGroupId() []byte {
	if m != nil {
		return m.CurrentTopGroupId
	}
	return nil
}

func (m *GroupRequestInfo) GetExistGroupIds() *GroupIdSlice {
	if m != nil {
		return m.ExistGroupIds
	}
	return nil
}

type Hashes struct {
	Hashes           [][]byte `protobuf:"bytes,1,rep,name=hashes" json:"hashes,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Hashes) Reset()                    { *m = Hashes{} }
func (m *Hashes) String() string            { return proto.CompactTextString(m) }
func (*Hashes) ProtoMessage()               {}
func (*Hashes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Hashes) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type TotalQnInfo struct {
	TotalQn          *uint64 `protobuf:"varint,1,req,name=TotalQn" json:"TotalQn,omitempty"`
	Height           *uint64 `protobuf:"varint,2,req,name=Height" json:"Height,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TotalQnInfo) Reset()                    { *m = TotalQnInfo{} }
func (m *TotalQnInfo) String() string            { return proto.CompactTextString(m) }
func (*TotalQnInfo) ProtoMessage()               {}
func (*TotalQnInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *TotalQnInfo) GetTotalQn() uint64 {
	if m != nil && m.TotalQn != nil {
		return *m.TotalQn
	}
	return 0
}

func (m *TotalQnInfo) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type StateInfoReq struct {
	Height           *uint64           `protobuf:"varint,1,req,name=Height" json:"Height,omitempty"`
	Transactions     *TransactionSlice `protobuf:"bytes,2,opt,name=Transactions" json:"Transactions,omitempty"`
	Addresses        [][]byte          `protobuf:"bytes,3,rep,name=Addresses" json:"Addresses,omitempty"`
	BlockHash        []byte            `protobuf:"bytes,4,req,name=BlockHash" json:"BlockHash,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *StateInfoReq) Reset()                    { *m = StateInfoReq{} }
func (m *StateInfoReq) String() string            { return proto.CompactTextString(m) }
func (*StateInfoReq) ProtoMessage()               {}
func (*StateInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *StateInfoReq) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *StateInfoReq) GetTransactions() *TransactionSlice {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *StateInfoReq) GetAddresses() [][]byte {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *StateInfoReq) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type StateInfo struct {
	Height            *uint64     `protobuf:"varint,1,req,name=Height" json:"Height,omitempty"`
	TrieNodes         []*TrieNode `protobuf:"bytes,2,rep,name=TrieNodes" json:"TrieNodes,omitempty"`
	BlockHash         []byte      `protobuf:"bytes,3,req,name=BlockHash" json:"BlockHash,omitempty"`
	ProBlockStateRoot []byte      `protobuf:"bytes,4,req,name=ProBlockStateRoot" json:"ProBlockStateRoot,omitempty"`
	XXX_unrecognized  []byte      `json:"-"`
}

func (m *StateInfo) Reset()                    { *m = StateInfo{} }
func (m *StateInfo) String() string            { return proto.CompactTextString(m) }
func (*StateInfo) ProtoMessage()               {}
func (*StateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *StateInfo) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *StateInfo) GetTrieNodes() []*TrieNode {
	if m != nil {
		return m.TrieNodes
	}
	return nil
}

func (m *StateInfo) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *StateInfo) GetProBlockStateRoot() []byte {
	if m != nil {
		return m.ProBlockStateRoot
	}
	return nil
}

type TrieNode struct {
	Key              []byte `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Data             []byte `protobuf:"bytes,2,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TrieNode) Reset()                    { *m = TrieNode{} }
func (m *TrieNode) String() string            { return proto.CompactTextString(m) }
func (*TrieNode) ProtoMessage()               {}
func (*TrieNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *TrieNode) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *TrieNode) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SignData struct {
	DataHash         []byte `protobuf:"bytes,1,req,name=DataHash" json:"DataHash,omitempty"`
	DataSign         []byte `protobuf:"bytes,2,req,name=DataSign" json:"DataSign,omitempty"`
	SignMember       []byte `protobuf:"bytes,3,req,name=SignMember" json:"SignMember,omitempty"`
	Version          *int32 `protobuf:"varint,4,opt,name=Version,def=0" json:"Version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SignData) Reset()                    { *m = SignData{} }
func (m *SignData) String() string            { return proto.CompactTextString(m) }
func (*SignData) ProtoMessage()               {}
func (*SignData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

const Default_SignData_Version int32 = 0

func (m *SignData) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *SignData) GetDataSign() []byte {
	if m != nil {
		return m.DataSign
	}
	return nil
}

func (m *SignData) GetSignMember() []byte {
	if m != nil {
		return m.SignMember
	}
	return nil
}

func (m *SignData) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_SignData_Version
}

type ConsensusGroupInitSummary struct {
	Header           *GroupHeader `protobuf:"bytes,1,req,name=Header" json:"Header,omitempty"`
	Signature        []byte       `protobuf:"bytes,2,req,name=Signature" json:"Signature,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ConsensusGroupInitSummary) Reset()                    { *m = ConsensusGroupInitSummary{} }
func (m *ConsensusGroupInitSummary) String() string            { return proto.CompactTextString(m) }
func (*ConsensusGroupInitSummary) ProtoMessage()               {}
func (*ConsensusGroupInitSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ConsensusGroupInitSummary) GetHeader() *GroupHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PubKeyInfo struct {
	ID               []byte `protobuf:"bytes,1,req,name=ID" json:"ID,omitempty"`
	PublicKey        []byte `protobuf:"bytes,2,req,name=PublicKey" json:"PublicKey,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PubKeyInfo) Reset()                    { *m = PubKeyInfo{} }
func (m *PubKeyInfo) String() string            { return proto.CompactTextString(m) }
func (*PubKeyInfo) ProtoMessage()               {}
func (*PubKeyInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *PubKeyInfo) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *PubKeyInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type ConsensusGroupInitInfo struct {
	GI               *ConsensusGroupInitSummary `protobuf:"bytes,1,req,name=GI" json:"GI,omitempty"`
	Mems             [][]byte                   `protobuf:"bytes,2,rep,name=Mems" json:"Mems,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ConsensusGroupInitInfo) Reset()                    { *m = ConsensusGroupInitInfo{} }
func (m *ConsensusGroupInitInfo) String() string            { return proto.CompactTextString(m) }
func (*ConsensusGroupInitInfo) ProtoMessage()               {}
func (*ConsensusGroupInitInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ConsensusGroupInitInfo) GetGI() *ConsensusGroupInitSummary {
	if m != nil {
		return m.GI
	}
	return nil
}

func (m *ConsensusGroupInitInfo) GetMems() [][]byte {
	if m != nil {
		return m.Mems
	}
	return nil
}

type ConsensusGroupRawMessage struct {
	GInfo            *ConsensusGroupInitInfo `protobuf:"bytes,1,req,name=GInfo" json:"GInfo,omitempty"`
	Sign             *SignData               `protobuf:"bytes,3,req,name=sign" json:"sign,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ConsensusGroupRawMessage) Reset()                    { *m = ConsensusGroupRawMessage{} }
func (m *ConsensusGroupRawMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusGroupRawMessage) ProtoMessage()               {}
func (*ConsensusGroupRawMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ConsensusGroupRawMessage) GetGInfo() *ConsensusGroupInitInfo {
	if m != nil {
		return m.GInfo
	}
	return nil
}

func (m *ConsensusGroupRawMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type SharePiece struct {
	Seckey           []byte `protobuf:"bytes,1,req,name=Seckey" json:"Seckey,omitempty"`
	Pubkey           []byte `protobuf:"bytes,2,req,name=Pubkey" json:"Pubkey,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SharePiece) Reset()                    { *m = SharePiece{} }
func (m *SharePiece) String() string            { return proto.CompactTextString(m) }
func (*SharePiece) ProtoMessage()               {}
func (*SharePiece) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *SharePiece) GetSeckey() []byte {
	if m != nil {
		return m.Seckey
	}
	return nil
}

func (m *SharePiece) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type ConsensusSharePieceMessage struct {
	GHash            []byte      `protobuf:"bytes,1,req,name=GHash" json:"GHash,omitempty"`
	Dest             []byte      `protobuf:"bytes,2,req,name=Dest" json:"Dest,omitempty"`
	SharePiece       *SharePiece `protobuf:"bytes,3,req,name=SharePiece" json:"SharePiece,omitempty"`
	MemCnt           *int32      `protobuf:"varint,4,req,name=MemCnt" json:"MemCnt,omitempty"`
	Sign             *SignData   `protobuf:"bytes,5,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ConsensusSharePieceMessage) Reset()                    { *m = ConsensusSharePieceMessage{} }
func (m *ConsensusSharePieceMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusSharePieceMessage) ProtoMessage()               {}
func (*ConsensusSharePieceMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ConsensusSharePieceMessage) GetGHash() []byte {
	if m != nil {
		return m.GHash
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetDest() []byte {
	if m != nil {
		return m.Dest
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetSharePiece() *SharePiece {
	if m != nil {
		return m.SharePiece
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetMemCnt() int32 {
	if m != nil && m.MemCnt != nil {
		return *m.MemCnt
	}
	return 0
}

func (m *ConsensusSharePieceMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusSignPubKeyMessage struct {
	GHash            []byte    `protobuf:"bytes,1,req,name=GHash" json:"GHash,omitempty"`
	GroupID          []byte    `protobuf:"bytes,2,req,name=GroupID" json:"GroupID,omitempty"`
	SignPK           []byte    `protobuf:"bytes,3,req,name=SignPK" json:"SignPK,omitempty"`
	MemCnt           *int32    `protobuf:"varint,4,req,name=MemCnt" json:"MemCnt,omitempty"`
	SignData         *SignData `protobuf:"bytes,5,req,name=SignData" json:"SignData,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ConsensusSignPubKeyMessage) Reset()                    { *m = ConsensusSignPubKeyMessage{} }
func (m *ConsensusSignPubKeyMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusSignPubKeyMessage) ProtoMessage()               {}
func (*ConsensusSignPubKeyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ConsensusSignPubKeyMessage) GetGHash() []byte {
	if m != nil {
		return m.GHash
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetSignPK() []byte {
	if m != nil {
		return m.SignPK
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetMemCnt() int32 {
	if m != nil && m.MemCnt != nil {
		return *m.MemCnt
	}
	return 0
}

func (m *ConsensusSignPubKeyMessage) GetSignData() *SignData {
	if m != nil {
		return m.SignData
	}
	return nil
}

type ConsensusSignPubkeyReqMessage struct {
	GroupID          []byte    `protobuf:"bytes,1,req,name=GroupID" json:"GroupID,omitempty"`
	SignData         *SignData `protobuf:"bytes,2,req,name=SignData" json:"SignData,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ConsensusSignPubkeyReqMessage) Reset()                    { *m = ConsensusSignPubkeyReqMessage{} }
func (m *ConsensusSignPubkeyReqMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusSignPubkeyReqMessage) ProtoMessage()               {}
func (*ConsensusSignPubkeyReqMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ConsensusSignPubkeyReqMessage) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusSignPubkeyReqMessage) GetSignData() *SignData {
	if m != nil {
		return m.SignData
	}
	return nil
}

type StaticGroupSummary struct {
	GroupID          []byte `protobuf:"bytes,1,req,name=GroupID" json:"GroupID,omitempty"`
	GroupPK          []byte `protobuf:"bytes,2,req,name=GroupPK" json:"GroupPK,omitempty"`
	GHash            []byte `protobuf:"bytes,3,req,name=GHash" json:"GHash,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StaticGroupSummary) Reset()                    { *m = StaticGroupSummary{} }
func (m *StaticGroupSummary) String() string            { return proto.CompactTextString(m) }
func (*StaticGroupSummary) ProtoMessage()               {}
func (*StaticGroupSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *StaticGroupSummary) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *StaticGroupSummary) GetGroupPK() []byte {
	if m != nil {
		return m.GroupPK
	}
	return nil
}

func (m *StaticGroupSummary) GetGHash() []byte {
	if m != nil {
		return m.GHash
	}
	return nil
}

type ConsensusGroupInitedMessage struct {
	GHash            []byte    `protobuf:"bytes,1,req,name=GHash" json:"GHash,omitempty"`
	GroupID          []byte    `protobuf:"bytes,2,req,name=GroupID" json:"GroupID,omitempty"`
	GroupPK          []byte    `protobuf:"bytes,3,req,name=GroupPK" json:"GroupPK,omitempty"`
	CreateHeight     *uint64   `protobuf:"varint,4,req,name=CreateHeight" json:"CreateHeight,omitempty"`
	ParentSign       []byte    `protobuf:"bytes,5,req,name=ParentSign" json:"ParentSign,omitempty"`
	MemMask          []byte    `protobuf:"bytes,6,req,name=MemMask" json:"MemMask,omitempty"`
	MemCnt           *int32    `protobuf:"varint,7,req,name=MemCnt" json:"MemCnt,omitempty"`
	Sign             *SignData `protobuf:"bytes,8,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ConsensusGroupInitedMessage) Reset()                    { *m = ConsensusGroupInitedMessage{} }
func (m *ConsensusGroupInitedMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusGroupInitedMessage) ProtoMessage()               {}
func (*ConsensusGroupInitedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *ConsensusGroupInitedMessage) GetGHash() []byte {
	if m != nil {
		return m.GHash
	}
	return nil
}

func (m *ConsensusGroupInitedMessage) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusGroupInitedMessage) GetGroupPK() []byte {
	if m != nil {
		return m.GroupPK
	}
	return nil
}

func (m *ConsensusGroupInitedMessage) GetCreateHeight() uint64 {
	if m != nil && m.CreateHeight != nil {
		return *m.CreateHeight
	}
	return 0
}

func (m *ConsensusGroupInitedMessage) GetParentSign() []byte {
	if m != nil {
		return m.ParentSign
	}
	return nil
}

func (m *ConsensusGroupInitedMessage) GetMemMask() []byte {
	if m != nil {
		return m.MemMask
	}
	return nil
}

func (m *ConsensusGroupInitedMessage) GetMemCnt() int32 {
	if m != nil && m.MemCnt != nil {
		return *m.MemCnt
	}
	return 0
}

func (m *ConsensusGroupInitedMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusCurrentMessage struct {
	GroupID          []byte    `protobuf:"bytes,1,opt,name=GroupID" json:"GroupID,omitempty"`
	PreHash          []byte    `protobuf:"bytes,2,req,name=PreHash" json:"PreHash,omitempty"`
	PreTime          []byte    `protobuf:"bytes,3,req,name=PreTime" json:"PreTime,omitempty"`
	BlockHeight      *uint64   `protobuf:"varint,4,req,name=BlockHeight" json:"BlockHeight,omitempty"`
	Sign             *SignData `protobuf:"bytes,6,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ConsensusCurrentMessage) Reset()                    { *m = ConsensusCurrentMessage{} }
func (m *ConsensusCurrentMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusCurrentMessage) ProtoMessage()               {}
func (*ConsensusCurrentMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *ConsensusCurrentMessage) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetPreTime() []byte {
	if m != nil {
		return m.PreTime
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetBlockHeight() uint64 {
	if m != nil && m.BlockHeight != nil {
		return *m.BlockHeight
	}
	return 0
}

func (m *ConsensusCurrentMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusCastMessage struct {
	Bh               *BlockHeader `protobuf:"bytes,1,req,name=Bh" json:"Bh,omitempty"`
	GroupID          []byte       `protobuf:"bytes,2,opt,name=GroupID" json:"GroupID,omitempty"`
	Sign             *SignData    `protobuf:"bytes,3,req,name=Sign" json:"Sign,omitempty"`
	ProveHash        [][]byte     `protobuf:"bytes,4,rep,name=ProveHash" json:"ProveHash,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ConsensusCastMessage) Reset()                    { *m = ConsensusCastMessage{} }
func (m *ConsensusCastMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusCastMessage) ProtoMessage()               {}
func (*ConsensusCastMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *ConsensusCastMessage) GetBh() *BlockHeader {
	if m != nil {
		return m.Bh
	}
	return nil
}

func (m *ConsensusCastMessage) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusCastMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *ConsensusCastMessage) GetProveHash() [][]byte {
	if m != nil {
		return m.ProveHash
	}
	return nil
}

type ConsensusVerifyMessage struct {
	BlockHash        []byte    `protobuf:"bytes,1,req,name=BlockHash" json:"BlockHash,omitempty"`
	RandomSign       []byte    `protobuf:"bytes,2,req,name=RandomSign" json:"RandomSign,omitempty"`
	Sign             *SignData `protobuf:"bytes,3,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ConsensusVerifyMessage) Reset()                    { *m = ConsensusVerifyMessage{} }
func (m *ConsensusVerifyMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusVerifyMessage) ProtoMessage()               {}
func (*ConsensusVerifyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *ConsensusVerifyMessage) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *ConsensusVerifyMessage) GetRandomSign() []byte {
	if m != nil {
		return m.RandomSign
	}
	return nil
}

func (m *ConsensusVerifyMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusBlockMessage struct {
	Block            *Block `protobuf:"bytes,1,req,name=Block" json:"Block,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ConsensusBlockMessage) Reset()                    { *m = ConsensusBlockMessage{} }
func (m *ConsensusBlockMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusBlockMessage) ProtoMessage()               {}
func (*ConsensusBlockMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *ConsensusBlockMessage) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type ConsensusCreateGroupRawMessage struct {
	GInfo            *ConsensusGroupInitInfo `protobuf:"bytes,1,req,name=GInfo" json:"GInfo,omitempty"`
	Sign             *SignData               `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ConsensusCreateGroupRawMessage) Reset()                    { *m = ConsensusCreateGroupRawMessage{} }
func (m *ConsensusCreateGroupRawMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusCreateGroupRawMessage) ProtoMessage()               {}
func (*ConsensusCreateGroupRawMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *ConsensusCreateGroupRawMessage) GetGInfo() *ConsensusGroupInitInfo {
	if m != nil {
		return m.GInfo
	}
	return nil
}

func (m *ConsensusCreateGroupRawMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusCreateGroupSignMessage struct {
	GHash            []byte    `protobuf:"bytes,1,req,name=GHash" json:"GHash,omitempty"`
	Sign             *SignData `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ConsensusCreateGroupSignMessage) Reset()         { *m = ConsensusCreateGroupSignMessage{} }
func (m *ConsensusCreateGroupSignMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusCreateGroupSignMessage) ProtoMessage()    {}
func (*ConsensusCreateGroupSignMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{38}
}

func (m *ConsensusCreateGroupSignMessage) GetGHash() []byte {
	if m != nil {
		return m.GHash
	}
	return nil
}

func (m *ConsensusCreateGroupSignMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type TopBlockInfo struct {
	Hash             []byte  `protobuf:"bytes,1,req,name=Hash" json:"Hash,omitempty"`
	TotalQn          *uint64 `protobuf:"varint,2,req,name=TotalQn" json:"TotalQn,omitempty"`
	Height           *uint64 `protobuf:"varint,3,req,name=Height" json:"Height,omitempty"`
	PreHash          []byte  `protobuf:"bytes,4,req,name=PreHash" json:"PreHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TopBlockInfo) Reset()                    { *m = TopBlockInfo{} }
func (m *TopBlockInfo) String() string            { return proto.CompactTextString(m) }
func (*TopBlockInfo) ProtoMessage()               {}
func (*TopBlockInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *TopBlockInfo) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *TopBlockInfo) GetTotalQn() uint64 {
	if m != nil && m.TotalQn != nil {
		return *m.TotalQn
	}
	return 0
}

func (m *TopBlockInfo) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *TopBlockInfo) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

type BlockMsgResponse struct {
	IsLast           *bool  `protobuf:"varint,1,req,name=IsLast" json:"IsLast,omitempty"`
	Block            *Block `protobuf:"bytes,2,opt,name=Block" json:"Block,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BlockMsgResponse) Reset()                    { *m = BlockMsgResponse{} }
func (m *BlockMsgResponse) String() string            { return proto.CompactTextString(m) }
func (*BlockMsgResponse) ProtoMessage()               {}
func (*BlockMsgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *BlockMsgResponse) GetIsLast() bool {
	if m != nil && m.IsLast != nil {
		return *m.IsLast
	}
	return false
}

func (m *BlockMsgResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type ChainPieceBlockMsg struct {
	TopHeader        *BlockHeader `protobuf:"bytes,1,req,name=TopHeader" json:"TopHeader,omitempty"`
	Blocks           []*Block     `protobuf:"bytes,2,rep,name=Blocks" json:"Blocks,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ChainPieceBlockMsg) Reset()                    { *m = ChainPieceBlockMsg{} }
func (m *ChainPieceBlockMsg) String() string            { return proto.CompactTextString(m) }
func (*ChainPieceBlockMsg) ProtoMessage()               {}
func (*ChainPieceBlockMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *ChainPieceBlockMsg) GetTopHeader() *BlockHeader {
	if m != nil {
		return m.TopHeader
	}
	return nil
}

func (m *ChainPieceBlockMsg) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type CreateGroupPingMessage struct {
	FromGroupID      []byte    `protobuf:"bytes,1,req,name=FromGroupID" json:"FromGroupID,omitempty"`
	PingID           *string   `protobuf:"bytes,2,req,name=PingID" json:"PingID,omitempty"`
	BaseHeight       *uint64   `protobuf:"varint,3,req,name=BaseHeight" json:"BaseHeight,omitempty"`
	Sign             *SignData `protobuf:"bytes,4,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CreateGroupPingMessage) Reset()                    { *m = CreateGroupPingMessage{} }
func (m *CreateGroupPingMessage) String() string            { return proto.CompactTextString(m) }
func (*CreateGroupPingMessage) ProtoMessage()               {}
func (*CreateGroupPingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *CreateGroupPingMessage) GetFromGroupID() []byte {
	if m != nil {
		return m.FromGroupID
	}
	return nil
}

func (m *CreateGroupPingMessage) GetPingID() string {
	if m != nil && m.PingID != nil {
		return *m.PingID
	}
	return ""
}

func (m *CreateGroupPingMessage) GetBaseHeight() uint64 {
	if m != nil && m.BaseHeight != nil {
		return *m.BaseHeight
	}
	return 0
}

func (m *CreateGroupPingMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type CreateGroupPongMessage struct {
	PingID           *string   `protobuf:"bytes,1,req,name=PingID" json:"PingID,omitempty"`
	Ts               []byte    `protobuf:"bytes,2,req,name=Ts" json:"Ts,omitempty"`
	Sign             *SignData `protobuf:"bytes,3,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CreateGroupPongMessage) Reset()                    { *m = CreateGroupPongMessage{} }
func (m *CreateGroupPongMessage) String() string            { return proto.CompactTextString(m) }
func (*CreateGroupPongMessage) ProtoMessage()               {}
func (*CreateGroupPongMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *CreateGroupPongMessage) GetPingID() string {
	if m != nil && m.PingID != nil {
		return *m.PingID
	}
	return ""
}

func (m *CreateGroupPongMessage) GetTs() []byte {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *CreateGroupPongMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ReqSharePieceMessage struct {
	GHash            []byte    `protobuf:"bytes,1,req,name=GHash" json:"GHash,omitempty"`
	Sign             *SignData `protobuf:"bytes,2,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ReqSharePieceMessage) Reset()                    { *m = ReqSharePieceMessage{} }
func (m *ReqSharePieceMessage) String() string            { return proto.CompactTextString(m) }
func (*ReqSharePieceMessage) ProtoMessage()               {}
func (*ReqSharePieceMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *ReqSharePieceMessage) GetGHash() []byte {
	if m != nil {
		return m.GHash
	}
	return nil
}

func (m *ReqSharePieceMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ResponseSharePieceMessage struct {
	GHash            []byte      `protobuf:"bytes,1,req,name=GHash" json:"GHash,omitempty"`
	SharePiece       *SharePiece `protobuf:"bytes,2,req,name=SharePiece" json:"SharePiece,omitempty"`
	Sign             *SignData   `protobuf:"bytes,3,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ResponseSharePieceMessage) Reset()                    { *m = ResponseSharePieceMessage{} }
func (m *ResponseSharePieceMessage) String() string            { return proto.CompactTextString(m) }
func (*ResponseSharePieceMessage) ProtoMessage()               {}
func (*ResponseSharePieceMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *ResponseSharePieceMessage) GetGHash() []byte {
	if m != nil {
		return m.GHash
	}
	return nil
}

func (m *ResponseSharePieceMessage) GetSharePiece() *SharePiece {
	if m != nil {
		return m.SharePiece
	}
	return nil
}

func (m *ResponseSharePieceMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type SubAccount struct {
	Balance          []byte  `protobuf:"bytes,1,opt,name=Balance" json:"Balance,omitempty"`
	Nonce            *uint64 `protobuf:"varint,2,opt,name=Nonce" json:"Nonce,omitempty"`
	Assets           []byte  `protobuf:"bytes,3,opt,name=Assets" json:"Assets,omitempty"`
	Ft               []byte  `protobuf:"bytes,4,opt,name=Ft" json:"Ft,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SubAccount) Reset()                    { *m = SubAccount{} }
func (m *SubAccount) String() string            { return proto.CompactTextString(m) }
func (*SubAccount) ProtoMessage()               {}
func (*SubAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *SubAccount) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *SubAccount) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *SubAccount) GetAssets() []byte {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *SubAccount) GetFt() []byte {
	if m != nil {
		return m.Ft
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "middleware.pb.Message")
	proto.RegisterType((*Transaction)(nil), "middleware.pb.Transaction")
	proto.RegisterType((*TransactionRequestMessage)(nil), "middleware.pb.TransactionRequestMessage")
	proto.RegisterType((*TrieNodes)(nil), "middleware.pb.TrieNodes")
	proto.RegisterType((*TransactionSlice)(nil), "middleware.pb.TransactionSlice")
	proto.RegisterType((*ChainPieceInfo)(nil), "middleware.pb.ChainPieceInfo")
	proto.RegisterType((*BlockHeader)(nil), "middleware.pb.BlockHeader")
	proto.RegisterType((*BlockBody)(nil), "middleware.pb.BlockBody")
	proto.RegisterType((*Block)(nil), "middleware.pb.Block")
	proto.RegisterType((*BlockSlice)(nil), "middleware.pb.BlockSlice")
	proto.RegisterType((*Member)(nil), "middleware.pb.Member")
	proto.RegisterType((*GroupHeader)(nil), "middleware.pb.GroupHeader")
	proto.RegisterType((*Group)(nil), "middleware.pb.Group")
	proto.RegisterType((*GroupInfo)(nil), "middleware.pb.GroupInfo")
	proto.RegisterType((*GroupSlice)(nil), "middleware.pb.GroupSlice")
	proto.RegisterType((*GroupIdSlice)(nil), "middleware.pb.GroupIdSlice")
	proto.RegisterType((*GroupRequestInfo)(nil), "middleware.pb.GroupRequestInfo")
	proto.RegisterType((*Hashes)(nil), "middleware.pb.Hashes")
	proto.RegisterType((*TotalQnInfo)(nil), "middleware.pb.TotalQnInfo")
	proto.RegisterType((*StateInfoReq)(nil), "middleware.pb.StateInfoReq")
	proto.RegisterType((*StateInfo)(nil), "middleware.pb.StateInfo")
	proto.RegisterType((*TrieNode)(nil), "middleware.pb.TrieNode")
	proto.RegisterType((*SignData)(nil), "middleware.pb.SignData")
	proto.RegisterType((*ConsensusGroupInitSummary)(nil), "middleware.pb.ConsensusGroupInitSummary")
	proto.RegisterType((*PubKeyInfo)(nil), "middleware.pb.PubKeyInfo")
	proto.RegisterType((*ConsensusGroupInitInfo)(nil), "middleware.pb.ConsensusGroupInitInfo")
	proto.RegisterType((*ConsensusGroupRawMessage)(nil), "middleware.pb.ConsensusGroupRawMessage")
	proto.RegisterType((*SharePiece)(nil), "middleware.pb.SharePiece")
	proto.RegisterType((*ConsensusSharePieceMessage)(nil), "middleware.pb.ConsensusSharePieceMessage")
	proto.RegisterType((*ConsensusSignPubKeyMessage)(nil), "middleware.pb.ConsensusSignPubKeyMessage")
	proto.RegisterType((*ConsensusSignPubkeyReqMessage)(nil), "middleware.pb.ConsensusSignPubkeyReqMessage")
	proto.RegisterType((*StaticGroupSummary)(nil), "middleware.pb.StaticGroupSummary")
	proto.RegisterType((*ConsensusGroupInitedMessage)(nil), "middleware.pb.ConsensusGroupInitedMessage")
	proto.RegisterType((*ConsensusCurrentMessage)(nil), "middleware.pb.ConsensusCurrentMessage")
	proto.RegisterType((*ConsensusCastMessage)(nil), "middleware.pb.ConsensusCastMessage")
	proto.RegisterType((*ConsensusVerifyMessage)(nil), "middleware.pb.ConsensusVerifyMessage")
	proto.RegisterType((*ConsensusBlockMessage)(nil), "middleware.pb.ConsensusBlockMessage")
	proto.RegisterType((*ConsensusCreateGroupRawMessage)(nil), "middleware.pb.ConsensusCreateGroupRawMessage")
	proto.RegisterType((*ConsensusCreateGroupSignMessage)(nil), "middleware.pb.ConsensusCreateGroupSignMessage")
	proto.RegisterType((*TopBlockInfo)(nil), "middleware.pb.TopBlockInfo")
	proto.RegisterType((*BlockMsgResponse)(nil), "middleware.pb.BlockMsgResponse")
	proto.RegisterType((*ChainPieceBlockMsg)(nil), "middleware.pb.ChainPieceBlockMsg")
	proto.RegisterType((*CreateGroupPingMessage)(nil), "middleware.pb.CreateGroupPingMessage")
	proto.RegisterType((*CreateGroupPongMessage)(nil), "middleware.pb.CreateGroupPongMessage")
	proto.RegisterType((*ReqSharePieceMessage)(nil), "middleware.pb.ReqSharePieceMessage")
	proto.RegisterType((*ResponseSharePieceMessage)(nil), "middleware.pb.ResponseSharePieceMessage")
	proto.RegisterType((*SubAccount)(nil), "middleware.pb.SubAccount")
}

func init() { proto.RegisterFile("x.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x06, 0xa9, 0xf3, 0x88, 0xf2, 0x81, 0xb6, 0x13, 0x3a, 0xc1, 0xff, 0x47, 0xe0, 0x1f, 0xff,
	0x50, 0x92, 0xc6, 0x08, 0x8c, 0x14, 0x05, 0x8a, 0xde, 0xc4, 0xb2, 0xe3, 0x18, 0x89, 0x0d, 0x55,
	0x16, 0x1c, 0xa0, 0xed, 0xcd, 0x9a, 0xdc, 0xc8, 0x84, 0x2d, 0x52, 0xde, 0x25, 0x1d, 0x1b, 0x45,
	0x81, 0xde, 0x35, 0x7d, 0x8a, 0xf6, 0x51, 0xfa, 0x40, 0xbd, 0xe9, 0x1b, 0x14, 0x3b, 0xbb, 0xcb,
	0x83, 0x2c, 0x4b, 0x4e, 0xd1, 0x2b, 0x61, 0x87, 0xbb, 0x33, 0xdf, 0xce, 0x7c, 0x73, 0x58, 0x41,
	0xed, 0x6a, 0x73, 0xcc, 0xa2, 0x38, 0xb2, 0x5b, 0xa3, 0xc0, 0xf7, 0xcf, 0xe9, 0x47, 0xc2, 0xe8,
	0xe6, 0xf8, 0xc4, 0xdd, 0x80, 0xda, 0x01, 0xe5, 0x9c, 0x0c, 0xa9, 0x6d, 0x41, 0xb9, 0x1b, 0xf9,
	0xd4, 0x31, 0xda, 0x46, 0xa7, 0x25, 0x56, 0xdb, 0x91, 0x7f, 0xed, 0x98, 0x6d, 0xa3, 0x63, 0xb9,
	0x7f, 0x19, 0xd0, 0x1c, 0x30, 0x12, 0x72, 0xe2, 0xc5, 0x41, 0x14, 0x8a, 0xaf, 0x3b, 0x24, 0x26,
	0x8e, 0xd1, 0x36, 0x3b, 0x0d, 0xbb, 0x05, 0x95, 0xc3, 0x28, 0xf4, 0x28, 0x6e, 0x2e, 0xdb, 0x0b,
	0x50, 0x3d, 0x8a, 0x12, 0xe6, 0x51, 0xa7, 0x24, 0x0e, 0x8b, 0xf5, 0x80, 0xb0, 0x21, 0x8d, 0x9d,
	0x32, 0x6e, 0xb7, 0xa0, 0x3c, 0xb8, 0x1e, 0x53, 0xa7, 0xd2, 0x36, 0x3b, 0x15, 0xb1, 0x7a, 0x43,
	0xf8, 0xa9, 0x53, 0xc5, 0xbd, 0xcb, 0xd0, 0xd8, 0xbd, 0x8a, 0x19, 0x41, 0xed, 0x35, 0x14, 0xad,
	0x41, 0x2b, 0x15, 0xe1, 0xb9, 0x7a, 0xdb, 0x90, 0xe7, 0x8e, 0x82, 0x61, 0xe8, 0x34, 0x70, 0x93,
	0xd0, 0x19, 0x8c, 0xa8, 0x03, 0x6d, 0xa3, 0xd3, 0x10, 0x5a, 0xfa, 0xf4, 0x22, 0xa1, 0x3c, 0xde,
	0xf7, 0x9d, 0x26, 0x82, 0xba, 0x0f, 0x8b, 0x47, 0x91, 0x77, 0x46, 0xe3, 0xec, 0x83, 0x85, 0x7b,
	0xc5, 0x87, 0xe4, 0x24, 0x77, 0x39, 0xee, 0xb4, 0xda, 0xa5, 0x4e, 0xc3, 0xbd, 0x84, 0xf5, 0x9c,
	0x54, 0x1d, 0xd3, 0xce, 0x5a, 0x87, 0xe5, 0xdc, 0x47, 0x71, 0x01, 0xca, 0x1d, 0xa3, 0x5d, 0xea,
	0x58, 0xb6, 0x03, 0x4b, 0xdd, 0x84, 0x31, 0x1a, 0xc6, 0xdb, 0xe7, 0x91, 0x77, 0x86, 0x97, 0x33,
	0xdb, 0x66, 0xc7, 0xb2, 0x57, 0xa0, 0x29, 0x45, 0x34, 0x18, 0x9e, 0xc6, 0x4e, 0xa9, 0x6d, 0x76,
	0xca, 0xf6, 0x22, 0xd4, 0x50, 0xd8, 0xbb, 0x44, 0xf7, 0x58, 0xee, 0x57, 0xd0, 0x18, 0xb0, 0x80,
	0x1e, 0x46, 0x3e, 0xe5, 0xf6, 0xd3, 0xdc, 0x02, 0xf5, 0x37, 0xb7, 0xee, 0x6f, 0x16, 0x42, 0xb8,
	0xa9, 0xbf, 0xbb, 0x3b, 0xb0, 0x94, 0xc3, 0x74, 0x74, 0x1e, 0x78, 0xd4, 0x7e, 0x01, 0x56, 0x9c,
	0xbf, 0x9a, 0x54, 0xf1, 0xe0, 0x86, 0x8a, 0x74, 0x8b, 0x7b, 0x01, 0x0b, 0xdd, 0x53, 0x12, 0x84,
	0xbd, 0x80, 0x7a, 0x74, 0x3f, 0xfc, 0x10, 0x09, 0x1d, 0x0a, 0x36, 0xf1, 0x29, 0xbb, 0x4d, 0x47,
	0x6e, 0x8b, 0xfd, 0x1c, 0x1a, 0x83, 0x68, 0x2c, 0x17, 0x78, 0xf7, 0x99, 0xdb, 0xdd, 0xdf, 0x4b,
	0xa9, 0x63, 0xf0, 0xb8, 0xa6, 0x84, 0xa1, 0xe9, 0xa3, 0x1c, 0x26, 0xe9, 0xb5, 0x08, 0xb5, 0x1e,
	0xa3, 0xb8, 0x41, 0xf2, 0x4b, 0x0a, 0x30, 0xfc, 0x65, 0x14, 0xd8, 0x00, 0x3d, 0x16, 0x5d, 0xd2,
	0x63, 0x72, 0x9e, 0x08, 0x9a, 0xa9, 0x4d, 0x83, 0x28, 0x26, 0xe7, 0xdf, 0x1e, 0x22, 0xd3, 0x50,
	0x4d, 0x37, 0x61, 0x78, 0xaa, 0xa6, 0xed, 0x74, 0x09, 0x8f, 0x23, 0x86, 0x04, 0xc3, 0x13, 0x7b,
	0x2c, 0x4a, 0xc6, 0xfb, 0xbe, 0xe2, 0xd8, 0x32, 0x34, 0x04, 0xe3, 0x48, 0x9c, 0x30, 0x49, 0x34,
	0x2b, 0x63, 0xbe, 0x24, 0xd9, 0xb3, 0x09, 0x6f, 0x0b, 0x86, 0x35, 0xb7, 0xd6, 0x26, 0xae, 0x2e,
	0xd9, 0x82, 0x69, 0x71, 0x35, 0x60, 0x94, 0x3a, 0x2d, 0xd4, 0xb5, 0x02, 0xcd, 0x3e, 0xf5, 0x68,
	0x30, 0x8e, 0x51, 0xb8, 0x90, 0xda, 0x8c, 0x49, 0x4c, 0x51, 0xb4, 0x78, 0x33, 0x45, 0x96, 0x34,
	0xf4, 0x3e, 0x09, 0xfd, 0x68, 0xe4, 0x2c, 0xeb, 0x2d, 0xe8, 0x80, 0x7e, 0x14, 0xc5, 0x8e, 0x8d,
	0xa2, 0x27, 0x00, 0xbb, 0x97, 0x81, 0x17, 0x53, 0x7f, 0x70, 0xc5, 0x9d, 0x95, 0x59, 0xc0, 0x6c,
	0x80, 0x34, 0x49, 0xb8, 0xb3, 0x8a, 0x05, 0xa0, 0x07, 0x0d, 0x8c, 0x90, 0xa8, 0x09, 0x42, 0x7d,
	0x46, 0x6d, 0x03, 0xa9, 0x3d, 0xc9, 0x33, 0x73, 0x2e, 0xcf, 0x28, 0x54, 0x50, 0x89, 0xfd, 0x54,
	0xc4, 0x17, 0x99, 0x62, 0xcc, 0x63, 0xca, 0x3f, 0x30, 0xb3, 0x05, 0x80, 0x0a, 0x64, 0x3a, 0x3c,
	0x86, 0x2a, 0xae, 0x34, 0x89, 0x57, 0xa7, 0xd9, 0x72, 0x1f, 0x43, 0xf5, 0x80, 0x8e, 0x4e, 0x28,
	0xb3, 0x01, 0xcc, 0x7d, 0x5f, 0x5d, 0x71, 0x01, 0xaa, 0xbd, 0xe4, 0xe4, 0x2d, 0xbd, 0x96, 0xd9,
	0xec, 0xfe, 0x69, 0x40, 0x13, 0x09, 0x72, 0x1b, 0x6b, 0x7b, 0x44, 0x14, 0x01, 0x59, 0x41, 0xed,
	0x25, 0xa8, 0xf7, 0x18, 0xc5, 0xfd, 0x98, 0xf8, 0x18, 0xa4, 0x57, 0x49, 0x7c, 0x1a, 0xb1, 0x20,
	0xbe, 0x46, 0xe2, 0x96, 0x85, 0x8a, 0x43, 0x32, 0x92, 0x94, 0xc5, 0x2a, 0xb6, 0x4d, 0x87, 0x41,
	0x88, 0x1c, 0xad, 0x6a, 0x66, 0x4b, 0x64, 0x18, 0x59, 0xc9, 0xdb, 0x55, 0xb0, 0xba, 0x8c, 0x92,
	0x98, 0xaa, 0x2c, 0xa9, 0xa3, 0x2a, 0x64, 0x13, 0xf1, 0xaf, 0x95, 0xb0, 0x81, 0x42, 0x1b, 0xe0,
	0x7d, 0xc4, 0x74, 0xfd, 0x01, 0x94, 0xad, 0x41, 0x6b, 0x27, 0xe0, 0xa3, 0x80, 0x73, 0x25, 0x6e,
	0xea, 0xf4, 0xd8, 0xbd, 0x8a, 0x69, 0xe8, 0x4b, 0x16, 0x37, 0xdc, 0x4f, 0x06, 0x54, 0x10, 0xfe,
	0xdc, 0x80, 0xe5, 0x9d, 0x22, 0x1d, 0x68, 0xa6, 0x2e, 0x91, 0x0e, 0x2c, 0xdd, 0xcc, 0xa7, 0xb2,
	0xce, 0x39, 0x79, 0x3f, 0xee, 0x54, 0xb0, 0x98, 0xae, 0xa4, 0x3e, 0x46, 0x6c, 0x98, 0xba, 0xee,
	0x2e, 0x34, 0x64, 0x66, 0x8a, 0xea, 0xf4, 0x18, 0xaa, 0xb8, 0xb8, 0x2d, 0xa4, 0x12, 0xb3, 0x0d,
	0xb0, 0xcf, 0x07, 0xd1, 0x58, 0x06, 0x40, 0x04, 0xb0, 0x2e, 0xa8, 0x81, 0xcb, 0x94, 0x1a, 0xf3,
	0xf5, 0xb8, 0x6d, 0xb0, 0x54, 0x51, 0x90, 0xa7, 0x96, 0xa0, 0xae, 0xd6, 0xaa, 0xfc, 0xbb, 0x04,
	0x96, 0x50, 0xa2, 0x53, 0x48, 0x60, 0x5c, 0x87, 0x65, 0xd5, 0x12, 0x34, 0x84, 0x94, 0x55, 0x5b,
	0xa2, 0xbb, 0x05, 0x3c, 0x4e, 0xb5, 0x98, 0x98, 0x9a, 0x0f, 0xa7, 0x59, 0x57, 0x46, 0x5d, 0x07,
	0xaa, 0x59, 0x0d, 0x39, 0xcd, 0xf5, 0x1e, 0x77, 0x13, 0x9a, 0xb2, 0xca, 0x85, 0x68, 0x37, 0x2d,
	0x7a, 0x21, 0x5a, 0x2b, 0x17, 0x6a, 0xa9, 0xd9, 0x29, 0xbb, 0x3f, 0x82, 0x85, 0xe5, 0x45, 0xec,
	0xee, 0xd3, 0x8b, 0xdc, 0x77, 0xb9, 0xff, 0x4b, 0xb0, 0x06, 0xc5, 0x7c, 0x13, 0xe0, 0x1e, 0xdd,
	0x9e, 0x6f, 0xd2, 0x2b, 0x82, 0xda, 0xbe, 0xcf, 0x28, 0xe7, 0x94, 0x3b, 0x25, 0x0c, 0x64, 0xa1,
	0x66, 0xc8, 0x46, 0x97, 0xa8, 0xda, 0x86, 0x50, 0x27, 0x2d, 0x17, 0x1a, 0x9f, 0x39, 0xb3, 0xf1,
	0x15, 0x75, 0xcb, 0xe4, 0x5a, 0x87, 0xe5, 0x1e, 0x8b, 0x64, 0xe6, 0x0b, 0x1b, 0x98, 0x2f, 0xd2,
	0xec, 0x06, 0xd4, 0xd3, 0x93, 0x4d, 0x28, 0x09, 0x3e, 0xca, 0x50, 0xe8, 0xa1, 0x46, 0xa6, 0xf7,
	0x31, 0xd4, 0x05, 0x3b, 0x85, 0x44, 0x44, 0x59, 0xfc, 0xe6, 0xea, 0x9d, 0x92, 0xe0, 0x04, 0x22,
	0x9b, 0xbb, 0x0d, 0x20, 0x56, 0x92, 0xbe, 0x0a, 0x85, 0x0d, 0xb5, 0x63, 0xca, 0x78, 0x10, 0x85,
	0xc8, 0xef, 0xca, 0xd7, 0xc6, 0x0b, 0xf7, 0x3b, 0x58, 0xef, 0x46, 0x21, 0xa7, 0x21, 0x4f, 0xb8,
	0x62, 0x71, 0x10, 0x1f, 0x25, 0xa3, 0x11, 0x61, 0xd7, 0x9f, 0x95, 0x5a, 0x85, 0xf4, 0x91, 0x98,
	0x9f, 0x01, 0xc8, 0x0c, 0x43, 0x97, 0x8a, 0xdc, 0xdb, 0x51, 0x78, 0x45, 0x47, 0x48, 0x4e, 0xce,
	0x03, 0x2f, 0xab, 0x5f, 0x3f, 0xc0, 0xbd, 0x9b, 0x40, 0xf0, 0xe0, 0x4b, 0x30, 0xf7, 0xf6, 0x15,
	0x82, 0xce, 0x04, 0x82, 0xdb, 0xb1, 0x5b, 0x50, 0x3e, 0xa0, 0x23, 0x19, 0x2c, 0xcb, 0xfd, 0x08,
	0x4e, 0x71, 0x6b, 0x9f, 0x7c, 0xd4, 0xc3, 0xd3, 0x4b, 0xa8, 0xec, 0x09, 0x43, 0xca, 0xc4, 0xc6,
	0x5c, 0x13, 0x88, 0x6a, 0x03, 0xca, 0x5c, 0xb8, 0xbb, 0x84, 0x87, 0x26, 0xc9, 0xa0, 0x63, 0xe5,
	0x7e, 0x01, 0x70, 0x74, 0x4a, 0x18, 0xc5, 0xf9, 0x05, 0x67, 0x51, 0xea, 0x9d, 0xa5, 0x31, 0x96,
	0x35, 0xe8, 0x2c, 0x75, 0xc2, 0x6f, 0x06, 0x3c, 0x48, 0xed, 0x65, 0xe7, 0x34, 0xd2, 0x16, 0x54,
	0xf6, 0x72, 0x51, 0x17, 0x0c, 0xa1, 0x3c, 0x56, 0x11, 0x7f, 0x9e, 0xb7, 0xa4, 0x60, 0xad, 0x4f,
	0xc2, 0x2a, 0x40, 0x39, 0xa0, 0xa3, 0x6e, 0x28, 0x79, 0x58, 0x11, 0xf7, 0x41, 0xfa, 0x54, 0x66,
	0xdf, 0xe7, 0x97, 0x02, 0xc2, 0x60, 0x18, 0xca, 0x08, 0xdf, 0x82, 0x30, 0x1d, 0x5a, 0x76, 0x14,
	0x48, 0xe1, 0x00, 0x71, 0xe8, 0xad, 0xa2, 0xe4, 0x24, 0x8a, 0x27, 0x19, 0xcd, 0xe7, 0x21, 0xf9,
	0x1e, 0xfe, 0x33, 0x09, 0xe4, 0x8c, 0x5e, 0xf7, 0xe9, 0x85, 0xc6, 0x92, 0x33, 0x2e, 0xd1, 0xe4,
	0x95, 0x9b, 0xb3, 0x95, 0xef, 0x82, 0x2d, 0x12, 0x35, 0xf0, 0x64, 0x49, 0x56, 0x9c, 0xba, 0xa1,
	0x51, 0x0b, 0x7a, 0x6f, 0xd5, 0xfd, 0xd2, 0xfb, 0xe3, 0xf5, 0xdc, 0x3f, 0x0c, 0x78, 0x78, 0x93,
	0x3f, 0xd4, 0xbf, 0xab, 0xbb, 0x72, 0xfa, 0xa5, 0xbf, 0x26, 0xbb, 0x6b, 0x19, 0xab, 0x93, 0x98,
	0x30, 0xb1, 0xbb, 0xa7, 0x11, 0xd4, 0xbd, 0xeb, 0x80, 0xf0, 0x33, 0xa7, 0x3a, 0xe1, 0xea, 0x5a,
	0x21, 0xe0, 0xf5, 0xd9, 0x9e, 0xf8, 0x64, 0xc0, 0xfd, 0xf4, 0x0a, 0xaa, 0x6d, 0x4c, 0xf5, 0x70,
	0x36, 0xfb, 0xe6, 0xde, 0x18, 0xb9, 0x61, 0xb8, 0x34, 0xed, 0xd1, 0x21, 0xf1, 0x6b, 0x28, 0xd5,
	0xd9, 0x50, 0x7e, 0x35, 0x60, 0x35, 0x83, 0x42, 0xb2, 0xe7, 0xcf, 0xff, 0xc1, 0xdc, 0x3e, 0xbd,
	0xc3, 0xbc, 0x56, 0xf0, 0xaf, 0xc0, 0xab, 0x0d, 0xcf, 0x4e, 0xe2, 0x74, 0x80, 0x55, 0xdd, 0x42,
	0x14, 0x94, 0x0f, 0xb9, 0x72, 0x75, 0x4c, 0x59, 0xf0, 0x21, 0x4d, 0x81, 0x29, 0xe3, 0xa8, 0x18,
	0x61, 0x71, 0x20, 0xce, 0x15, 0xe8, 0xbb, 0x99, 0x76, 0xbf, 0x81, 0xb5, 0xd4, 0x0e, 0xaa, 0xd5,
	0x66, 0xfe, 0xa7, 0x06, 0x56, 0x75, 0xed, 0xe9, 0xa3, 0xe3, 0x4f, 0xf0, 0xdf, 0xcc, 0x61, 0xc8,
	0x9b, 0x7f, 0xb7, 0xf8, 0xcd, 0xc9, 0xa2, 0xf7, 0xf0, 0x68, 0x9a, 0x79, 0xd9, 0x98, 0xa6, 0x66,
	0xc0, 0x1d, 0x15, 0x1f, 0x82, 0x35, 0x88, 0xc6, 0x78, 0x47, 0xc4, 0x93, 0x0d, 0xbb, 0x66, 0xfe,
	0x71, 0x25, 0xf5, 0xe4, 0xe7, 0x8c, 0xf4, 0x91, 0xab, 0x69, 0x2a, 0x9b, 0xf0, 0x1e, 0x2c, 0x49,
	0xe7, 0xf2, 0x61, 0x9f, 0xf2, 0xb1, 0xc0, 0x2c, 0x0e, 0xed, 0xf3, 0x77, 0x84, 0xcb, 0x11, 0xa0,
	0x9e, 0x39, 0x5c, 0x4e, 0x1d, 0xd3, 0x1d, 0x1e, 0x80, 0x9d, 0x3d, 0x57, 0xb5, 0xca, 0xe2, 0x03,
	0x74, 0x3e, 0x4d, 0xb3, 0x67, 0x81, 0x39, 0xe3, 0x59, 0x70, 0x05, 0xf7, 0x72, 0x3e, 0xed, 0x05,
	0xe1, 0x50, 0xfb, 0x74, 0x05, 0x9a, 0xaf, 0x59, 0x34, 0x2a, 0x96, 0x2a, 0xd1, 0x6a, 0x82, 0x70,
	0xa8, 0x4a, 0x4b, 0x43, 0x70, 0x72, 0x9b, 0x70, 0x5a, 0xf0, 0x8b, 0xe6, 0x64, 0x79, 0x5e, 0xe5,
	0x2d, 0x58, 0x8e, 0x32, 0xcb, 0x99, 0x11, 0xf9, 0x57, 0x0c, 0x80, 0x39, 0xe0, 0x9f, 0x47, 0xf8,
	0x77, 0xb0, 0xda, 0xa7, 0x17, 0x73, 0x7b, 0x9f, 0xd6, 0x36, 0x87, 0x28, 0x3f, 0x1b, 0xb0, 0xae,
	0x23, 0x3a, 0x57, 0x67, 0xb1, 0x83, 0x9a, 0xf3, 0x3a, 0xe8, 0x1d, 0x2f, 0xf4, 0x06, 0xe0, 0x28,
	0x39, 0x79, 0xe5, 0x79, 0x51, 0x12, 0xc6, 0xf8, 0xff, 0x0a, 0x39, 0x27, 0xe2, 0x91, 0x6e, 0x14,
	0xdf, 0xec, 0xe9, 0xbf, 0x55, 0xaf, 0x38, 0xa7, 0x31, 0x57, 0xaf, 0x12, 0x00, 0xf3, 0x75, 0x2c,
	0x9f, 0x23, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xd7, 0xc6, 0xcf, 0x36, 0x13, 0x00, 0x00,
}
